//! Pairing protocol: mutual registration of two machines as peers.
//!
//! Pairing runs on a dedicated ALPN, separate from the sync protocol: it is
//! the only protocol accepting connections from unknown endpoints, gated by a
//! one-time secret carried in the pairing ticket instead of the peer
//! allowlist. Endpoint identities themselves are authenticated by iroh's QUIC
//! handshake, so the exchange only has to carry the human names.
//!
//! Flow, over a single bidirectional stream:
//! 1. joiner -> host: [`Message::Hello`] with the ticket secret and the
//!    joiner's name
//! 2. host -> joiner: [`Message::Welcome`] with the host's name, or
//!    [`Message::Reject`]
//! 3. joiner -> host: [`Message::Done`], or [`Message::Reject`]
//!
//! Each side validates the announced peer against its own configuration
//! before answering, so no side persists a peer the other refused.
//! Registration itself happens outside the protocol though: a connection loss
//! at the very end or a failed config write can still leave the machines half
//! paired. Removing the peer entry and re-pairing recovers.

use std::{fmt, str::FromStr, time::Duration};

use color_eyre::eyre::{Context, Result, bail, ensure, eyre};
use data_encoding::BASE32_NOPAD;
use iroh::{
    Endpoint, EndpointAddr, EndpointId,
    endpoint::{Connection, ConnectionError, SendStream, VarInt},
};
use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq as _;

use super::{
    bind_endpoint,
    wire::{read_message, write_message},
};
use crate::config::{Config, MachineKey};

/// ALPN of the pairing protocol.
pub const ALPN: &[u8] = b"jj-mesh/pair/0";

/// Prefix of the ticket serialization.
const TICKET_PREFIX: &str = "jjmesh-pair-";

/// Maximum accepted size of a protocol message.
const MAX_MESSAGE_SIZE: u32 = 4096;

/// How long the host waits for a relay connection when issuing a ticket.
const ONLINE_TIMEOUT: Duration = Duration::from_secs(30);

/// Time budget for one connection to complete the whole exchange. Keeps
/// stalled or malicious connections from blocking the host's wait, since the
/// pairing ALPN accepts connections from unknown endpoints.
const EXCHANGE_TIMEOUT: Duration = Duration::from_secs(15);

/// How long a rejecting side waits for the peer to close before giving up.
const REJECT_LINGER: Duration = Duration::from_secs(5);

/// Ticket generated by the pairing host, transmitted out-of-band to the
/// joining machine. Contains everything needed to reach the host directly
/// (bypassing discovery, which may not have propagated yet) and the one-time
/// secret authorizing the join.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairTicket {
    addr: EndpointAddr,
    secret: PairSecret,
}

impl fmt::Display for PairTicket {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let bytes = postcard::to_stdvec(self).expect("ticket must serialize");
        let encoded = BASE32_NOPAD.encode(&bytes).to_ascii_lowercase();
        write!(f, "{TICKET_PREFIX}{encoded}")
    }
}

impl FromStr for PairTicket {
    type Err = color_eyre::eyre::Error;

    fn from_str(s: &str) -> Result<Self> {
        let encoded = s
            .trim()
            .strip_prefix(TICKET_PREFIX)
            .ok_or_else(|| eyre!("not a jj-mesh pairing ticket"))?;
        let bytes = BASE32_NOPAD
            .decode(encoded.to_ascii_uppercase().as_bytes())
            .wrap_err("invalid pairing ticket")?;

        let (ticket, rest) =
            postcard::take_from_bytes(&bytes).wrap_err("invalid pairing ticket")?;
        ensure!(rest.is_empty(), "invalid pairing ticket: trailing bytes");

        Ok(ticket)
    }
}

/// One-time random secret authorizing a join against a pairing host.
#[derive(Clone, Serialize, Deserialize)]
struct PairSecret([u8; 16]);

impl PairSecret {
    fn generate() -> Self {
        PairSecret(rand::random())
    }

    /// Constant-time comparison, to not leak the secret through timing.
    fn verify(&self, candidate: &PairSecret) -> bool {
        self.0.ct_eq(&candidate.0).into()
    }
}

impl fmt::Debug for PairSecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("PairSecret(..)")
    }
}

/// The peer registered by a successful pairing.
#[derive(Debug, Clone)]
pub struct PairedPeer {
    /// Name the peer announced.
    pub name: String,
    /// Endpoint id of the peer, authenticated by the connection handshake.
    pub endpoint: EndpointId,
}

/// A protocol message. Every message is sent by a single side, but they share
/// one enum as the wire format.
#[derive(Debug, Serialize, Deserialize)]
enum Message {
    /// Joiner's opening request, proving ticket possession.
    Hello { secret: PairSecret, name: String },
    /// Host's acceptance, announcing its own name.
    Welcome { name: String },
    /// Joiner's confirmation that it accepts the pairing.
    Done,
    /// Refusal, sent by either side instead of `Welcome`/`Done`.
    Reject { reason: String },
}

/// Host side of a pairing exchange.
///
/// Binding and waiting are split so the caller can display the ticket before
/// blocking on the peer.
#[derive(Debug)]
pub struct PairHost {
    endpoint: Endpoint,
    ticket: PairTicket,
}

impl PairHost {
    /// Binds the endpoint, waits until it is reachable and issues a ticket.
    pub async fn bind(key: &MachineKey) -> Result<Self> {
        let endpoint = bind_endpoint(key, vec![ALPN.to_vec()]).await?;

        // Wait for a relay connection so the ticket contains a usable
        // relay address even before hole punching is possible.
        tokio::time::timeout(ONLINE_TIMEOUT, endpoint.online())
            .await
            .map_err(|_| eyre!("cannot reach an iroh relay, check network connectivity"))?;

        let ticket = PairTicket {
            addr: endpoint.addr(),
            secret: PairSecret::generate(),
        };

        Ok(PairHost { endpoint, ticket })
    }

    /// The ticket to transmit out-of-band to the joining machine.
    pub fn ticket(&self) -> &PairTicket {
        &self.ticket
    }

    /// Waits for a machine holding the ticket and exchanges identities with
    /// it. Returns once one pairing succeeds; invalid or interrupted attempts
    /// are shed without ending the wait.
    pub async fn wait_for_peer(self, local_name: &str, config: &Config) -> Result<PairedPeer> {
        let result = accept_loop(&self.endpoint, &self.ticket.secret, local_name, config).await;
        self.endpoint.close().await;
        result
    }
}

/// Accepts connections sequentially until one completes the exchange, giving
/// each connection [`EXCHANGE_TIMEOUT`] before shedding it.
async fn accept_loop(
    endpoint: &Endpoint,
    secret: &PairSecret,
    local_name: &str,
    config: &Config,
) -> Result<PairedPeer> {
    loop {
        let Some(incoming) = endpoint.accept().await else {
            bail!("endpoint closed while waiting for a peer");
        };
        let Ok(connecting) = incoming.accept() else {
            continue;
        };
        let Ok(conn) = connecting.await else {
            continue;
        };

        let exchange = pair_with(&conn, secret, local_name, config);
        match tokio::time::timeout(EXCHANGE_TIMEOUT, exchange).await {
            Ok(Ok(Some(peer))) => return Ok(peer),
            // Invalid or interrupted attempt: keep waiting.
            Ok(Ok(None)) => {}
            Ok(Err(err)) => return Err(err),
            Err(_timeout) => conn.close(0u32.into(), b"timeout"),
        }
    }
}

/// Runs the host side of the exchange on one connection.
///
/// Returns `Ok(None)` when the attempt failed without needing user action
/// (invalid ticket, connection trouble) and waiting should continue. Errors
/// are terminal: the user must intervene before pairing can proceed.
async fn pair_with(
    conn: &Connection,
    secret: &PairSecret,
    local_name: &str,
    config: &Config,
) -> Result<Option<PairedPeer>> {
    let Ok((mut send, mut recv)) = conn.accept_bi().await else {
        return Ok(None);
    };

    // Joiners that don't speak the protocol or hold the wrong secret are
    // dismissed without stopping the host.
    let hello = match read_message(&mut recv, MAX_MESSAGE_SIZE).await {
        Ok(Message::Hello {
            secret: proof,
            name,
        }) if secret.verify(&proof) => name,
        Ok(_) | Err(_) => {
            send_reject(conn, &mut send, "invalid pairing ticket").await;
            return Ok(None);
        }
    };

    let endpoint = conn.remote_id();
    if let Err(err) = config.validate_new_peer(&hello, &endpoint) {
        send_reject(conn, &mut send, &err.to_string()).await;
        return Err(err.wrap_err("cannot pair"));
    }

    let welcome = Message::Welcome {
        name: local_name.to_owned(),
    };
    if write_message(&mut send, &welcome, MAX_MESSAGE_SIZE)
        .await
        .is_err()
    {
        return Ok(None);
    }

    match read_message(&mut recv, MAX_MESSAGE_SIZE).await {
        Ok(Message::Done) => {}
        Ok(Message::Reject { reason }) => bail!("peer rejected pairing: {reason}"),
        Ok(msg) => bail!("unexpected message from peer: {msg:?}"),
        // Connection lost mid-exchange: let the joiner retry with the same
        // ticket instead of tearing the window down.
        Err(_) => return Ok(None),
    }

    conn.close(0u32.into(), b"paired");
    Ok(Some(PairedPeer {
        name: hello,
        endpoint,
    }))
}

/// Joiner side: connects to the ticket's host and exchanges identities.
pub async fn join(
    key: &MachineKey,
    ticket: &PairTicket,
    local_name: &str,
    config: &Config,
) -> Result<PairedPeer> {
    ensure!(
        ticket.addr.id != key.endpoint_id(),
        "cannot pair a machine with itself",
    );

    let endpoint = bind_endpoint(key, vec![]).await?;
    let result = join_with(&endpoint, ticket, local_name, config).await;
    endpoint.close().await;
    result
}

/// Runs the joiner side of the exchange on a fresh connection to the host.
async fn join_with(
    endpoint: &Endpoint,
    ticket: &PairTicket,
    local_name: &str,
    config: &Config,
) -> Result<PairedPeer> {
    let conn = endpoint
        .connect(ticket.addr.clone(), ALPN)
        .await
        .wrap_err("cannot connect to the pairing host")?;
    let (mut send, mut recv) = conn.open_bi().await?;

    let hello = Message::Hello {
        secret: ticket.secret.clone(),
        name: local_name.to_owned(),
    };
    write_message(&mut send, &hello, MAX_MESSAGE_SIZE).await?;

    let host_endpoint = conn.remote_id();
    let name = match read_message(&mut recv, MAX_MESSAGE_SIZE).await? {
        Message::Welcome { name } => name,
        Message::Reject { reason } => {
            conn.close(0u32.into(), b"rejected");
            bail!("pairing rejected: {reason}");
        }
        msg => bail!("unexpected message from host: {msg:?}"),
    };

    if let Err(err) = config.validate_new_peer(&name, &host_endpoint) {
        send_reject(&conn, &mut send, &err.to_string()).await;
        return Err(err.wrap_err("cannot pair"));
    }

    write_message(&mut send, &Message::Done, MAX_MESSAGE_SIZE).await?;
    let _ = send.finish();

    // The host closes with "paired" once it has read `Done`; any other close
    // reason means the host may not have registered us.
    match conn.closed().await {
        ConnectionError::ApplicationClosed(close) if close.error_code == VarInt::from_u32(0) => {}
        reason => bail!(
            "connection lost before pairing completed ({reason}); \
             check `jj-mesh peers` on the other machine before retrying",
        ),
    }

    Ok(PairedPeer {
        name,
        endpoint: host_endpoint,
    })
}

/// Sends a rejection, waiting for the peer to see it before closing: closing
/// right after the write would discard the queued message.
async fn send_reject(conn: &Connection, send: &mut SendStream, reason: &str) {
    let reject = Message::Reject {
        reason: reason.to_owned(),
    };

    if write_message(send, &reject, MAX_MESSAGE_SIZE).await.is_ok() && send.finish().is_ok() {
        let _ = tokio::time::timeout(REJECT_LINGER, conn.closed()).await;
    }
    conn.close(0u32.into(), b"rejected");
}

#[cfg(test)]
mod tests {
    use iroh::SecretKey;

    use super::*;

    #[test]
    fn ticket_roundtrip() {
        let ticket = PairTicket {
            addr: EndpointAddr::from(SecretKey::generate().public()),
            secret: PairSecret::generate(),
        };

        let parsed: PairTicket = ticket.to_string().parse().unwrap();
        assert_eq!(parsed.addr, ticket.addr);
        assert!(ticket.secret.verify(&parsed.secret));
    }

    #[test]
    fn ticket_rejects_garbage() {
        assert!("jjmesh-pair-notbase32!".parse::<PairTicket>().is_err());
        assert!("some-other-ticket".parse::<PairTicket>().is_err());

        // Trailing data must be rejected, not silently ignored.
        let ticket = PairTicket {
            addr: EndpointAddr::from(SecretKey::generate().public()),
            secret: PairSecret::generate(),
        };
        let padded = format!("{ticket}aaaaaaaa");
        assert!(padded.parse::<PairTicket>().is_err());
    }

    #[test]
    fn secret_verification() {
        let secret = PairSecret::generate();
        assert!(secret.verify(&secret.clone()));
        assert!(!secret.verify(&PairSecret::generate()));
    }
}
