//! Pairing protocol: mutual registration of two machines as peers.
//!
//! Pairing runs on a dedicated ALPN, separate from the sync protocol: it is
//! the only protocol accepting connections from unknown endpoints, gated by a
//! one-time secret carried in the pairing ticket instead of the peer
//! allowlist. Endpoint identities themselves are authenticated by iroh's QUIC
//! handshake, so the exchange only has to carry the human names.
//!
//! Flow, over a single bidirectional stream:
//! 1. joiner -> host: [`Message::Hello`] with the ticket secret and the
//!    joiner's name
//! 2. host -> joiner: [`Message::Welcome`] with the host's name, or
//!    [`Message::Reject`]
//! 3. joiner -> host: [`Message::Done`], or [`Message::Reject`]
//!
//! Each side validates the announced peer against its own mesh state
//! before answering, so no side persists a peer the other refused. The host
//! persists the peer before confirming with the `paired` close (the joiner's
//! commit signal, see [`confirm_paired`]), so it can never confirm a peer it
//! did not save. The joiner persists after that close: a failure there can
//! still leave the host paired one-sidedly. Pairing an already-registered
//! endpoint is idempotent (identities are authenticated by the handshake),
//! so a half-paired machine recovers by simply pairing again.

use std::{fmt, str::FromStr, time::Duration};

use color_eyre::eyre::{Context, Result, bail, ensure, eyre};
use data_encoding::BASE32_NOPAD;
use iroh::{
    Endpoint, EndpointAddr, EndpointId,
    endpoint::{Connection, ConnectionError, SendStream, VarInt},
};
use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq as _;

use super::wire::{read_message, write_message};
use crate::config::MeshState;

/// ALPN of the pairing protocol.
pub const ALPN: &[u8] = b"jj-mesh/pair/0";

/// Prefix of the ticket serialization.
const TICKET_PREFIX: &str = "jjmesh-pair-";

/// Maximum accepted size of a protocol message.
const MAX_MESSAGE_SIZE: u32 = 4096;

/// Host-side budget for a connection to open its stream and present its
/// `Hello`. This pre-secret phase is the only part an attacker without the
/// ticket can stretch, and one stalled connection occupies one of the few
/// exchange slots, so it gets a much shorter deadline than the exchange.
const HELLO_TIMEOUT: Duration = Duration::from_secs(5);

/// How long a rejecting side waits for the peer to close before giving up.
const REJECT_LINGER: Duration = Duration::from_secs(5);

/// Linger for rejections of unauthenticated attempts: anyone can trigger
/// those, so the courtesy has to be cheap to keep pairing responsive.
const REJECT_LINGER_BRIEF: Duration = Duration::from_secs(1);

/// Close reason confirming a successful pairing to the joiner.
const PAIRED_REASON: &[u8] = b"paired";

/// Ticket generated by the pairing host, transmitted out-of-band to the
/// joining machine. Contains everything needed to reach the host directly
/// (bypassing discovery, which may not have propagated yet) and the one-time
/// secret authorizing the join.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PairTicket {
    addr: EndpointAddr,
    secret: PairSecret,
}

impl PairTicket {
    /// Issues a ticket, with a fresh secret, for a host reachable at `addr`.
    pub fn generate(addr: EndpointAddr) -> Self {
        PairTicket {
            addr,
            secret: PairSecret::generate(),
        }
    }

    /// Whether `other` is the same issued ticket (same secret).
    pub(crate) fn matches(&self, other: &PairTicket) -> bool {
        self.secret.verify(&other.secret)
    }
}

impl fmt::Display for PairTicket {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let bytes = postcard::to_stdvec(self).expect("ticket must serialize");
        let encoded = BASE32_NOPAD.encode(&bytes).to_ascii_lowercase();
        write!(f, "{TICKET_PREFIX}{encoded}")
    }
}

impl FromStr for PairTicket {
    type Err = color_eyre::eyre::Error;

    fn from_str(s: &str) -> Result<Self> {
        let encoded = s
            .trim()
            .strip_prefix(TICKET_PREFIX)
            .ok_or_else(|| eyre!("not a jj-mesh pairing ticket"))?;
        let bytes = BASE32_NOPAD
            .decode(encoded.to_ascii_uppercase().as_bytes())
            .wrap_err("invalid pairing ticket")?;

        let (ticket, rest) =
            postcard::take_from_bytes(&bytes).wrap_err("invalid pairing ticket")?;
        ensure!(rest.is_empty(), "invalid pairing ticket: trailing bytes");

        Ok(ticket)
    }
}

/// One-time random secret authorizing a join against a pairing host.
#[derive(Clone, Serialize, Deserialize)]
struct PairSecret([u8; 16]);

impl PairSecret {
    fn generate() -> Self {
        PairSecret(rand::random())
    }

    /// Constant-time comparison, to not leak the secret through timing.
    fn verify(&self, candidate: &PairSecret) -> bool {
        self.0.ct_eq(&candidate.0).into()
    }
}

impl fmt::Debug for PairSecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("PairSecret(..)")
    }
}

/// The peer registered by a successful pairing.
#[derive(Debug, Clone)]
pub struct PairedPeer {
    /// Name the peer announced.
    pub name: String,
    /// Endpoint id of the peer, authenticated by the connection handshake.
    pub endpoint: EndpointId,
}

/// A protocol message. Every message is sent by a single side, but they share
/// one enum as the wire format.
#[derive(Debug, Serialize, Deserialize)]
enum Message {
    /// Joiner's opening request, proving ticket possession.
    Hello { secret: PairSecret, name: String },
    /// Host's acceptance, announcing its own name.
    Welcome { name: String },
    /// Joiner's confirmation that it accepts the pairing.
    Done,
    /// Refusal, sent by either side instead of `Welcome`/`Done`.
    Reject { reason: String },
}

/// Runs the host side of the exchange on one connection, accepted on the
/// pairing ALPN with `ticket` outstanding.
///
/// Returns `Ok(None)` when the attempt failed without needing user action
/// (invalid ticket, connection trouble). Errors mean an attempt by the
/// ticket holder itself failed (it was sent the reason); the caller
/// decides whether the ticket stays redeemable.
///
/// On success the connection is left open: the caller must persist the peer
/// and then call [`confirm_paired`]. Closing any other way (including by
/// dropping the connection) makes the joiner treat the pairing as failed.
pub async fn pair_with(
    conn: &Connection,
    ticket: &PairTicket,
    local_name: &str,
    state: &MeshState,
) -> Result<Option<PairedPeer>> {
    let opening = tokio::time::timeout(HELLO_TIMEOUT, async {
        let (send, mut recv) = conn.accept_bi().await.ok()?;
        let hello = read_message(&mut recv, MAX_MESSAGE_SIZE).await;
        Some((send, recv, hello))
    })
    .await;
    let (mut send, mut recv, hello) = match opening {
        Ok(Some(opened)) => opened,
        Ok(None) => return Ok(None),
        Err(_timeout) => {
            conn.close(0u32.into(), b"timeout");
            return Ok(None);
        }
    };

    // Joiners that don't speak the protocol or hold the wrong secret are
    // dismissed without stopping the host.
    let hello = match hello {
        Ok(Message::Hello {
            secret: proof,
            name,
        }) if ticket.secret.verify(&proof) => name,
        Ok(_) | Err(_) => {
            send_reject(
                conn,
                &mut send,
                "invalid pairing ticket",
                REJECT_LINGER_BRIEF,
            )
            .await;
            return Ok(None);
        }
    };

    let endpoint = conn.remote_id();
    // Re-pairing an already-registered machine is idempotent, keeping its
    // stored name: accepting a peer we already trust gives an attacker
    // nothing, and lets a half-paired joiner recover by retrying.
    let name = if let Some(existing) = state.peer_name(&endpoint) {
        existing.to_owned()
    } else {
        if let Err(err) = state.validate_new_peer(&hello, &endpoint) {
            send_reject(conn, &mut send, &err.to_string(), REJECT_LINGER).await;
            return Err(err.wrap_err("cannot pair"));
        }
        hello
    };

    let welcome = Message::Welcome {
        name: local_name.to_owned(),
    };
    if write_message(&mut send, &welcome, MAX_MESSAGE_SIZE)
        .await
        .is_err()
    {
        return Ok(None);
    }

    match read_message(&mut recv, MAX_MESSAGE_SIZE).await {
        Ok(Message::Done) => {}
        Ok(Message::Reject { reason }) => bail!(
            "peer rejected pairing: {}",
            crate::config::sanitize(&reason)
        ),
        Ok(msg) => bail!("unexpected message from peer: {msg:?}"),
        // Connection lost mid-exchange: let the joiner retry with the same
        // ticket instead of failing the attempt for good.
        Err(_) => return Ok(None),
    }

    Ok(Some(PairedPeer { name, endpoint }))
}

/// Host side for connections arriving while no ticket is outstanding:
/// answers the joiner's opening stream with a rejection, so it sees a
/// readable reason instead of a transport error.
pub async fn reject_attempt(conn: &Connection, reason: &str) {
    // The joiner's Hello is left unread but its stream is kept open until
    // the linger, so the joiner's write cannot fail before it reads the
    // rejection.
    match tokio::time::timeout(HELLO_TIMEOUT, conn.accept_bi()).await {
        Ok(Ok((mut send, _recv))) => {
            send_reject(conn, &mut send, reason, REJECT_LINGER_BRIEF).await;
        }
        Ok(Err(_)) | Err(_) => conn.close(0u32.into(), b"timeout"),
    }
}

/// Confirms a successful pairing to the joiner.
///
/// This close is the joiner's commit signal: the caller must have persisted
/// the peer already, so the host never confirms a peer it did not save.
pub fn confirm_paired(conn: &Connection) {
    conn.close(0u32.into(), PAIRED_REASON);
}

/// Joiner side: connects to the ticket's host with `endpoint` (which stays
/// open, the caller owns it) and exchanges identities.
pub async fn join(
    endpoint: &Endpoint,
    ticket: &PairTicket,
    local_name: &str,
    state: &MeshState,
) -> Result<PairedPeer> {
    ensure!(
        ticket.addr.id != endpoint.secret_key().public(),
        "cannot pair a machine with itself",
    );

    let conn = endpoint
        .connect(ticket.addr.clone(), ALPN)
        .await
        .wrap_err("cannot connect to the pairing host")?;
    let (mut send, mut recv) = conn.open_bi().await?;

    let hello = Message::Hello {
        secret: ticket.secret.clone(),
        name: local_name.to_owned(),
    };
    write_message(&mut send, &hello, MAX_MESSAGE_SIZE).await?;

    let host_endpoint = conn.remote_id();
    let name = match read_message(&mut recv, MAX_MESSAGE_SIZE).await? {
        Message::Welcome { name } => name,
        Message::Reject { reason } => {
            conn.close(0u32.into(), b"rejected");
            bail!("pairing rejected: {}", crate::config::sanitize(&reason));
        }
        msg => bail!("unexpected message from host: {msg:?}"),
    };

    // Mirror of the host's idempotent re-pairing: a host we already have
    // registered keeps its stored name.
    let name = if let Some(existing) = state.peer_name(&host_endpoint) {
        existing.to_owned()
    } else {
        if let Err(err) = state.validate_new_peer(&name, &host_endpoint) {
            send_reject(&conn, &mut send, &err.to_string(), REJECT_LINGER).await;
            return Err(err.wrap_err("cannot pair"));
        }
        name
    };

    write_message(&mut send, &Message::Done, MAX_MESSAGE_SIZE).await?;
    let _ = send.finish();

    // The host closes with "paired" once it has persisted the peer; any
    // other close (including the code-0 close of a dropped connection, e.g.
    // the host revoking the ticket) means the host did not register us.
    match conn.closed().await {
        ConnectionError::ApplicationClosed(close)
            if close.error_code == VarInt::from_u32(0)
                && close.reason.as_ref() == PAIRED_REASON => {}
        reason => bail!(
            "connection lost before pairing completed ({reason}); \
             check `jj-mesh peers` on the other machine before retrying",
        ),
    }

    Ok(PairedPeer {
        name,
        endpoint: host_endpoint,
    })
}

/// Sends a rejection, waiting up to `linger` for the peer to see it before
/// closing: closing right after the write would discard the queued message.
async fn send_reject(conn: &Connection, send: &mut SendStream, reason: &str, linger: Duration) {
    let reject = Message::Reject {
        reason: reason.to_owned(),
    };

    if write_message(send, &reject, MAX_MESSAGE_SIZE).await.is_ok() && send.finish().is_ok() {
        let _ = tokio::time::timeout(linger, conn.closed()).await;
    }
    conn.close(0u32.into(), b"rejected");
}

#[cfg(test)]
mod tests {
    use iroh::SecretKey;

    use super::*;

    #[test]
    fn ticket_roundtrip() {
        let ticket = PairTicket {
            addr: EndpointAddr::from(SecretKey::generate().public()),
            secret: PairSecret::generate(),
        };

        let parsed: PairTicket = ticket.to_string().parse().unwrap();
        assert_eq!(parsed.addr, ticket.addr);
        assert!(ticket.secret.verify(&parsed.secret));
    }

    #[test]
    fn ticket_rejects_garbage() {
        assert!("jjmesh-pair-notbase32!".parse::<PairTicket>().is_err());
        assert!("some-other-ticket".parse::<PairTicket>().is_err());

        // Trailing data must be rejected, not silently ignored.
        let ticket = PairTicket {
            addr: EndpointAddr::from(SecretKey::generate().public()),
            secret: PairSecret::generate(),
        };
        let padded = format!("{ticket}aaaaaaaa");
        assert!(padded.parse::<PairTicket>().is_err());
    }

    #[test]
    fn secret_verification() {
        let secret = PairSecret::generate();
        assert!(secret.verify(&secret.clone()));
        assert!(!secret.verify(&PairSecret::generate()));
    }
}
